
import type { Product } from './types';

export const allProducts: Product[] = [
    {
        id: 48082,
        name: "Lote Giordani Gold Essenza Supreme",
        brand: "Giordani Gold",
        price: 49.99,
        regularPrice: 85.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48082%2F48082_1.png",
        description: "El epítome del lujo supremo. Incluye Perfume Essenza Supreme con tapa de oro de 24k y crema corporal perfumada en caja magenta premium.",
        stock: 15,
        category: "perfume",
        tag: "SET",
        rating: 5.0,
        reviewCount: 24,
        beautyPoints: 120
    },
    {
        id: 1475,
        name: "Milk & Honey Gold Crema de Manos y Cuerpo",
        brand: "Milk & Honey",
        price: 8.49,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F31602%2F31602_1.png",
        description: "Nutrición intensa para pieles secas con extractos de origen orgánico de leche y miel. Textura suntuosa.",
        stock: 27,
        category: "personal-care",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 450
    },
    {
        id: 1477,
        name: "Milk & Honey Magnolia Majestic",
        brand: "Milk & Honey",
        price: 9.99,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42869%2F42869_1.png",
        description: "Edición limitada de lujo. Fragancia floral de magnolia con la suavidad legendaria de la leche y la miel.",
        stock: 28,
        category: "personal-care",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 85
    },
    {
        id: 48115,
        name: "Crema de Día Reafirmante SPF 20 Royal Velvet",
        brand: "Royal Velvet",
        price: 18.47,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48115%2F48115_1.png",
        description: "Enriquecida con infusión de Iris Negro para reafirmar y fortalecer la piel a partir de los 40 años.",
        stock: 12,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 92
    },
    {
        id: 42813,
        name: "Eau de Toilette Eclat Homme",
        brand: "Eclat",
        price: 24.99,
        regularPrice: 46.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42813%2F42813_1.png",
        description: "Fragancia atemporal con notas de Cidro y Cuero de Barenia. Elegancia masculina pura.",
        stock: 40,
        category: "men",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 156
    },
    {
        id: 44952,
        name: "Pasta de Dientes Optifresh Maximum Fresh",
        brand: "Optifresh",
        price: 4.49,
        regularPrice: 9.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44952%2F44952_1.png",
        description: "Protección total para tu boca con tecnología Shield y sabor a menta refrescante.",
        stock: 200,
        category: "personal-care",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 230
    },
    {
        id: 13659,
        name: "Crema Antienvejecimiento Diamond Cellular",
        brand: "Diamond Cellular",
        price: 29.99,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F13659%2F13659_1.png",
        description: "Lujoso tratamiento con polvo de diamante que ilumina y regenera la piel a nivel celular.",
        stock: 15,
        category: "skincare",
        tag: "OFERTA",
        rating: 5.0,
        reviewCount: 312
    },
    {
        id: 44955,
        name: "Champú Color Protect Duologi",
        brand: "Duologi",
        price: 7.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44955%2F44955_1.png",
        description: "Champú híbrido que limpia y protege la vitalidad del color en cabellos teñidos.",
        stock: 55,
        category: "hair",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 42
    },
    {
        id: 44961,
        name: "Acondicionador Ligero Duologi",
        brand: "Duologi",
        price: 7.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44961%2F44961_1.png",
        description: "Nutrición sin peso para cabellos finos. Deja el pelo sedoso y manejable.",
        stock: 60,
        category: "hair",
        tag: "NOVEDAD",
        rating: 4.7,
        reviewCount: 38
    },
    {
        id: 1467,
        name: "Crema Corporal Perfumada Divine",
        brand: "Divine",
        price: 8.49,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41545%2F41545_1.png",
        description: "Hidratación profunda con la sofisticada fragancia Divine de lirio y fresia.",
        stock: 24,
        category: "personal-care",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 189
    },
    {
        id: 44098,
        name: "Tratamiento de Día SPF 30 Novage+",
        brand: "Novage+",
        price: 19.24,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44098%2F44098_1.png",
        description: "Crema de día multi-correctora con bioactivadores avanzados para combatir arrugas y manchas.",
        stock: 120,
        category: "skincare",
        tag: "OFERTA",
        rating: 5.0,
        reviewCount: 650
    }
];
