
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- NUEVOS PRODUCTOS CATÁLOGO 1 - 2026 (De CSV) ---
    {
        id: 47188,
        name: "Iluminador Líquido Illuskin THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png",
        description: "Iluminador líquido versátil para un brillo natural o intenso. Mezclable y modulable.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.7,
        reviewCount: 54
    },
    {
        id: 46134,
        name: "BB Cream Beautifier MAX SPF 15 THE ONE",
        brand: "The ONE",
        price: 5.77,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png",
        description: "BB Cream multifuncional que hidrata, corrige y protege. Acabado natural.",
        stock: 289,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 142
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 16.93,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png",
        description: "Perlas bronceadoras infusionadas con serum antiedad. Edición limitada.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 82
    },
    {
        id: 46940,
        name: "Stick Iluminador con Color THE ONE",
        brand: "The ONE",
        price: 7.69,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46940%2F46940_1.png",
        description: "Iluminador en barra fácil de aplicar para un brillo radiante al instante.",
        stock: 80,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 552
    },
    {
        id: 46906,
        name: "Maquillaje Everlasting Sync SPF 20 THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46906%2F46906_1.png",
        description: "Base de maquillaje inteligente que se adapta a tu piel y al entorno.",
        stock: 75,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 1038
    },
    {
        id: 42121,
        name: "Paleta Ojos y Rostro Fabulous Beauty GG",
        brand: "Giordani Gold",
        price: 19.24,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42121%2F42121_1.png",
        description: "Paleta todo en uno de lujo para ojos y rostro. Pigmentación intensa y sedosa.",
        stock: 40,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 371
    },
    {
        id: 46319,
        name: "Niacinamida 10% Power Drops Novage+",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46319%2F46319_1.png",
        description: "Potenciador con Niacinamida para fortalecer la barrera cutánea y mejorar la textura.",
        stock: 160,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 160
    },
    {
        id: 48675,
        name: "Caja de Regalo Crema Universal - Turquesa",
        brand: "Crema Universal",
        price: 13.85,
        regularPrice: 36.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48675%2F48675_1.png",
        description: "Trío de cremas universales: Grosella Negra, Original y Ciruela Dulce.",
        stock: 100,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 5.0,
        reviewCount: 45
    },
    {
        id: 48648,
        name: "Caja Regalo: Original, Pasión y Manzana",
        brand: "Crema Universal",
        price: 10.77,
        regularPrice: 36.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48648%2F48648_1.png",
        description: "Set de regalo con tres variantes deliciosas de la clásica Crema Universal.",
        stock: 1167,
        category: "skincare",
        tag: "SET",
        rating: 4.9,
        reviewCount: 212
    },
    {
        id: 46992,
        name: "Mascarilla Gel to Ice Mango Orgánico",
        brand: "Love Nature",
        price: 2.30,
        regularPrice: 6.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46992%2F46992_1.png",
        description: "Mascarilla refrescante de mango para una piel radiante.",
        stock: 468,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 468
    },
    {
        id: 46990,
        name: "Mascarilla Gel to Ice Sandía Orgánica",
        brand: "Love Nature",
        price: 2.30,
        regularPrice: 6.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46990%2F46990_1.png",
        description: "Mascarilla hidratante de sandía. Úsala fría para un efecto calmante.",
        stock: 567,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 567
    },
    {
        id: 47502,
        name: "Mister Giordani Aqua Eau de Parfum",
        brand: "Giordani Gold",
        price: 29.99,
        regularPrice: 44.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47502%2F47502_1.png",
        description: "Fragancia acuática y refinada para el hombre moderno. Una escapada a la costa italiana.",
        stock: 50,
        category: "men",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 120
    },
    // --- PRODUCTOS ANTERIORES PRESERVADOS ---
    {
        id: 38497,
        name: "Divine Eau de Parfum",
        brand: "Divine",
        price: 26.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png",
        description: "Fragancia icónica con notas de Orquídea y Almizcle. Elegancia en estado puro.",
        stock: 40,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 150
    },
    {
        id: 46642,
        name: "Jabón Líquido Manos Limón y Verbena",
        brand: "Essense & Co",
        price: 15.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46642%2F46642_1.png",
        description: "Elegante jabón líquido con aceites naturales de limón y verbena.",
        stock: 30,
        category: "personal-care",
        rating: 4.7,
        reviewCount: 80
    },
    {
        id: 43237,
        name: "Barra Labios Colour Stylist Ultimate",
        brand: "The ONE",
        price: 9.99,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43237%2F43237_1.png",
        description: "Color intenso y cobertura total en una sola pasada. Acabado cremoso.",
        stock: 120,
        category: "makeup",
        rating: 4.7,
        reviewCount: 320
    }
];
